/**
 * Optional pre-compilation pass that renames local bindings to random identifiers.
 *
 * Uses the naming system's {@link NameScope} for name generation — same
 * PRNG, character sets, and length tiers as the VM runtime identifiers.
 * Preprocessed names blend in with the runtime names in the final output.
 *
 * @module preprocess
 */

import { parse } from "@babel/parser";
import { BABEL_PARSER_PLUGINS, GLOBAL_IDENTIFIERS } from "./constants.js";
import { traverse, generate } from "./babel-compat.js";
import { NameScope } from "./naming/scope.js";
import { RESERVED_WORDS, EXCLUDED_NAMES } from "./naming/reserved.js";

// --- Types ---

export interface PreprocessResult {
	code: string;
	usedNames: Set<string>;
}

// --- Public API ---

/**
 * Rename all local bindings to random short identifiers.
 * Global identifiers are skipped.
 *
 * Uses the naming system's {@link NameScope} for name generation (same
 * PRNG and character sets as runtime identifiers). Collision avoidance
 * against reserved words, globals, and previously generated names.
 *
 * @param source - JavaScript source code to preprocess.
 * @param seed   - Build seed for deterministic PRNG-based name generation.
 * @returns The source with local bindings renamed, plus the set of generated names.
 */
export function preprocessIdentifiers(
	source: string,
	seed: number
): PreprocessResult {
	const ast = parse(source, {
		sourceType: "unambiguous",
		plugins: [...BABEL_PARSER_PLUGINS],
	});

	// Use the naming system's NameScope for generation (same PRNG + charset)
	const scope = new NameScope("preprocess", seed, "short");

	// Exclusion set: reserved words + globals + naming system exclusions
	const used = new Set<string>([...RESERVED_WORDS, ...EXCLUDED_NAMES]);
	for (const g of GLOBAL_IDENTIFIERS) used.add(g);

	// Track names generated by this pass (for NameRegistry collision avoidance)
	const generatedNames = new Set<string>();

	const MAX_RETRIES = 50;

	function generateName(): string {
		let lengthBump = 0;
		let retries = 0;

		for (;;) {
			let candidate = scope.generateCandidate();
			// Adaptive length bump: append extra chars when collisions accumulate
			if (lengthBump > 0 && candidate.length < 2 + lengthBump) {
				const ALNUM =
					"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
				while (candidate.length < 2 + lengthBump) {
					candidate += ALNUM[scope.nextPrng() % ALNUM.length]!;
				}
			}

			if (!used.has(candidate)) {
				used.add(candidate);
				generatedNames.add(candidate);
				return candidate;
			}

			retries++;
			if (retries > MAX_RETRIES) {
				lengthBump++;
				retries = 0;
			}
		}
	}

	// --- Collect bindings to rename ---
	const toRename: { scope: any; name: string }[] = [];

	traverse(ast, {
		Scope(path) {
			for (const name of Object.keys(path.scope.bindings)) {
				if ((GLOBAL_IDENTIFIERS as ReadonlySet<string>).has(name))
					continue;
				toRename.push({ scope: path.scope, name });
			}
		},
	});

	// --- Rename (scope.rename handles AST mutation correctly) ---
	const renamed = new Set<object>();

	for (const { scope, name } of toRename) {
		const binding = scope.bindings[name];
		if (!binding) continue; // may have been removed by a prior rename
		if (renamed.has(binding)) continue;
		renamed.add(binding);

		const newName = generateName();
		scope.rename(name, newName);
	}

	return {
		code: generate(ast).code,
		usedNames: generatedNames,
	};
}
